package framework.command;

import java.util.Date;

//
//
// Generated by StarUML(tm) Java Add-In
//
// @ Project : Financial Application Framework
// @ File Name : AbstractCommand.java
// @ Date : 4/21/2014
// @ Author : Batjargal Batbold, Jose Ardaiz, Ripon Datta
//
//

public abstract class AbstractCommand implements ICommand {
	protected String			name;
	protected CommandManager	commandManager;
	protected Date				createdDate;
	protected Date				executionDate;
	protected boolean			execute	= true;

	public AbstractCommand(String name) {
		this.name = name;
		createdDate = new Date();
	}

	@Override
	public Date getExecutionDate() {
		return executionDate;
	}

	@Override
	public void setExecutionDate(Date executionDate) {
		this.executionDate = executionDate;
	}

	@Override
	public Date getCreatedDate() {
		return createdDate;
	}

	@Override
	public String getName() {
		return name;
	}

	@Override
	public boolean getExecute() {
		return execute;
	}

	@Override
	public void setExecute(boolean execute) {
		this.execute = execute;
	}

	@Override
	public void setCommandManager(CommandManager cm) {
		this.commandManager = cm;
	}
}
