package framework.command;

import framework.account.IAccount;
import framework.customer.ICustomer;
//
//
// Generated by StarUML(tm) Java Add-In
//
// @ Project : Financial Application Framework
// @ File Name : AddAccount.java
// @ Date : 4/21/2014
// @ Author : Batjargal Batbold, Jose Ardaiz, Ripon Datta
//
//

public class AddAccount extends AbstractCommand {
	private ICustomer	customer;
	private IAccount	account;

	/**
	 * Adds the given account to the customer
	 * @param customer Customer
	 * @param account Account to add
	 */
	public AddAccount(ICustomer customer, IAccount account) {
		super("Add account");
		this.customer = customer;
		this.account = account;
	}

	@Override
	public void execute() {
		// Pre check
		if (execute) {
			commandManager.getContext().getCustomerManager().addCustomer(customer);
			customer.addAccount(account);
		}
	}
}
