package framework.command;

import java.util.Date;

//
//
// Generated by StarUML(tm) Java Add-In
//
// @ Project : Financial Application Framework
// @ File Name : CommandManagerProxy.java
// @ Date : 4/21/2014
// @ Author : Batjargal Batbold, Jose Ardaiz, Ripon Datta
//
//

public class CommandProxy implements ICommand {
	private ICommand				command;
	private ICommandProxyFunctor	functor;

	public CommandProxy(ICommand command, ICommandProxyFunctor f) {
		this.command = command;
		this.functor = f;
	}

	@Override
	public void execute() {
		functor.preProcess();
		// Execute real command
		command.execute();
		// Set executed date
		command.setExecutionDate(new Date());
		functor.postProcess();
	}

	@Override
	public String getName() {
		return command.getName();
	}

	@Override
	public Date getCreatedDate() {
		return command.getCreatedDate();
	}

	@Override
	public Date getExecutionDate() {
		return command.getExecutionDate();
	}

	@Override
	public void setExecutionDate(Date date) {
		command.setExecutionDate(date);
	}

	@Override
	public boolean getExecute() {
		return command.getExecute();
	}

	@Override
	public void setExecute(boolean execute) {
		command.setExecute(execute);
	}

	@Override
	public void setCommandManager(CommandManager cm) {
		command.setCommandManager(cm);
	}
}
