package framework.command;

import java.util.LinkedList;
//
//
// Generated by StarUML(tm) Java Add-In
//
// @ Project : Financial Application Framework
// @ File Name : CommandManager.java
// @ Date : 4/21/2014
// @ Author : Batjargal Batbold, Jose Ardaiz, Ripon Datta
//
//

import framework.FinancialCompanyApplication;

public class CommandManager extends Thread {
	private FinancialCompanyApplication context;
	private LinkedList<ICommand>	commandQueue;
	private LinkedList<ICommand>	commandHistory;

	public CommandManager(FinancialCompanyApplication context) {
		this.context = context;
		commandQueue = new LinkedList<ICommand>();
		commandHistory = new LinkedList<ICommand>();
	}

	@Override
	public void run() {
		while (commandQueue.size() > 0) {
			ICommand c = commandQueue.pop();
			CommandProxy logger = new CommandProxy(c, new LoggingFunctor(c));
			logger.execute();
			commandHistory.push(c);
		}
	}

	public void sendCommand(ICommand command) {
		command.setCommandManager(this);
		commandQueue.push(command);
		this.run();
	}

	@Override
	public String toString() {
		StringBuilder str = new StringBuilder("Commands:\n");
		for (ICommand c : commandHistory) {
			str.append(c + "\n");
		}
		return str.toString();
	}

	public FinancialCompanyApplication getContext() {
		return context;
	}
}
