package framework.command;

import java.util.Date;

//
//
// Generated by StarUML(tm) Java Add-In
//
// @ Project : Financial Application Framework
// @ File Name : ICommand.java
// @ Date : 4/21/2014
// @ Author : Batjargal Batbold, Jose Ardaiz, Ripon Datta
//
//

public interface ICommand {
	/**
	 * Executes the given command
	 */
	public void execute();

	/**
	 * Returns the name of command. The name is usually the class name
	 * @return Command name
	 */
	public String getName();

	/**
	 * The date when the command was created. Auto-initialized
	 * @return Command created date
	 */
	public Date getCreatedDate();

	/**
	 * The execution date of the command. Auto-initialized after execution
	 * @return Command execution date
	 */
	public Date getExecutionDate();

	/**
	 * Set execution date
	 */
	public void setExecutionDate(Date date);

	/**
	 * Get boolean value if the command should be executed
	 * @return Execute true|false
	 */
	public boolean getExecute();

	/**
	 * Set if the command should executed
	 */
	public void setExecute(boolean execute);
	
	public void setCommandManager(CommandManager cm);
}
