package framework.command;

//
//
// Generated by StarUML(tm) Java Add-In
//
// @ Project : Financial Application Framework
// @ File Name : ProxyLogger.java
// @ Date : 4/21/2014
// @ Author : Batjargal Batbold, Jose Ardaiz, Ripon Datta
//
//

public class LoggingFunctor implements ICommandProxyFunctor {
	private ICommand	command;

	public LoggingFunctor(ICommand command) {
		this.command = command;
	}

	@Override
	public void preProcess() {
		log("Command: " + command.getName() + "[Cr:" + command.getCreatedDate() + "] started execution ");
	}

	@Override
	public void postProcess() {
		log("Command: " + command.getName() + "[Ex:" + command.getExecutionDate() + "] finished execution");
	}

	private void log(String str) {
		System.out.println(str);
	}

}
