package framework.command;

import framework.account.Entry;
import framework.account.IAccount;
//
//
// Generated by StarUML(tm) Java Add-In
//
// @ Project : Financial Application Framework
// @ File Name : Withdraw.java
// @ Date : 4/21/2014
// @ Author : Batjargal Batbold, Jose Ardaiz, Ripon Datta
//
//

public class Withdraw extends AbstractCommand {
	private IAccount	account;
	private Entry		entry;

	public Withdraw(IAccount account, Entry entry) {
		super("Withdraw from account");
		this.account = account;
		this.entry = entry;
	}

	@Override
	public void execute() {
		if (account.getCustomer() == null) {
			setExecute(false);
			System.err.println("[Withdraw PreExecution error] Account not bound to any customer");
		}
		double amount = Math.abs(entry.getAmount());
		if (amount > account.getBalance()) {
			setExecute(false);
			System.err.println("[Withdraw PreExecution error] Account balance not sufficient");
		}
		if (execute) {
			if (!account.withdraw(entry)) {
				System.err.println("[Withdraw Execution error] Please check amount or account state");
				setExecute(false);
			}
		}
	}
}
