package framework.customer;

import java.util.Vector;

//
//
// Generated by StarUML(tm) Java Add-In
//
// @ Project : Financial Application Framework
// @ File Name : Company.java
// @ Date : 4/21/2014
// @ Author : Batjargal Batbold, Jose Ardaiz, Ripon Datta
//
//

public class Company extends BaseCustomer implements ICompany {

	private int				noEmployees;
	private Vector<IPerson>	employees;

	public Company(String name, String street, String city, String state, String zip, String email,
					int noEmployees) {
		super(name, street, city, state, zip, email);
		this.noEmployees = noEmployees;
		employees = new Vector<IPerson>();
	}

	public int getNoEmployees() {
		return noEmployees;
	}

	public void setNoEmployees(int noEmployees) {
		this.noEmployees = noEmployees;
	}

	public Vector<IPerson> getEmployees() {
		return employees;
	}

	public void setEmployees(Vector<IPerson> employees) {
		this.employees = employees;
	}

	@Override
	public void addEmployee(IPerson employee) {
		employees.add(employee);
	}

}
