package framework.customer;

import java.util.Vector;

import framework.account.IAccount;
//
//
// Generated by StarUML(tm) Java Add-In
//
// @ Project : Financial Application Framework
// @ File Name : ICustomer.java
// @ Date : 4/21/2014
// @ Author : Batjargal Batbold, Jose Ardaiz, Ripon Datta
//
//

public interface ICustomer {
	public void addAccount(IAccount account);

	public Vector<IAccount> getAccounts();

	public String getBill();

	public String getName();

	public String getStreet();

	public String getCity();

	public String getState();

	public String getZip();

	public String getAddress();

	public String getEmail();

	public void setName(String name);

	public void setStreet(String street);

	public void setCity(String city);

	public void setState(String state);

	public void setZip(String zip);

	public void setEmail(String email);
}
