package framework.customer;

import java.util.Date;
//
//
// Generated by StarUML(tm) Java Add-In
//
// @ Project : Financial Application Framework
// @ File Name : Person.java
// @ Date : 4/21/2014
// @ Author : Batjargal Batbold, Jose Ardaiz, Ripon Datta
//
//

public class Person extends BaseCustomer implements IPerson {
	private Date	birthday;

	public Person(String name, String street, String city, String state, String zip, String email,
					Date birthDay) {
		super(name, street, city, state, zip, email);
		this.birthday = birthDay;
	}

	public Date getBirthday() {
		return birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

}
