package framework.factory;

import framework.account.BaseAccount;
import framework.account.IAccount;
//
//
// Generated by StarUML(tm) Java Add-In
//
// @ Project : Financial Application Framework
// @ File Name : AbstractAccountFactory.java
// @ Date : 4/21/2014
// @ Author : Batjargal Batbold, Jose Ardaiz, Ripon Datta
//
//
import framework.customer.ICustomer;

public class AccountFactory extends AbstractFactory<IAccount> {
	private ICustomer customer;
	public AccountFactory(ICustomer customer){
		this.customer = customer; 
	}
	

	@Override
	public IAccount make() {
		item = new BaseAccount(customer);
		return item;
	}

}
