package framework.account;

//
//
// Generated by StarUML(tm) Java Add-In
//
// @ Project : Financial Application Framework
// @ File Name : AccountStateInTransaction.java
// @ Date : 4/21/2014
// @ Author : Batjargal Batbold, Jose Ardaiz, Ripon Datta
//
//

public class AccountStateInTransaction implements IAccountState {
	private static AccountStateInTransaction	instance	= new AccountStateInTransaction();

	public static AccountStateInTransaction getInstance() {
		return instance;
	}

	@Override
	public boolean deposit(BaseAccount account, Entry entry) {
		System.err.println("Deposit failed on account in transaction: " + account);
		return false;
	}

	@Override
	public boolean withdraw(BaseAccount account, Entry entry) {
		System.err.println("Withdraw failed on account in transaction: " + account);
		return false;
	}

}
