package framework.account;

//
//
// Generated by StarUML(tm) Java Add-In
//
// @ Project : Financial Application Framework
// @ File Name : AccountStateActive.java
// @ Date : 4/21/2014
// @ Author : Batjargal Batbold, Jose Ardaiz, Ripon Datta
//
//

public class AccountStateActive implements IAccountState {
	private static AccountStateActive	instance	= new AccountStateActive();

	public static AccountStateActive getInstance() {
		return instance;
	}

	@Override
	public boolean deposit(BaseAccount account, Entry entry) {
		// For better perfomance visibility sleep for 0-20 seconds
		// Random r = new Random();
		try {
			account.setState(AccountStateInTransaction.getInstance());
			// Thread.sleep(r.nextInt(20) * 1000);
			Thread.sleep(1);
			account.addEntry(entry);

			account.setState(AccountStateActive.getInstance());
			return true;
		} catch (InterruptedException e) {
			e.printStackTrace();
		}

		return true;
	}

	@Override
	public boolean withdraw(BaseAccount account, Entry entry) {
		// For better perfomance visibility sleep for 0-4 seconds
		// Random r = new Random();
		try {
			account.setState(AccountStateInTransaction.getInstance());
			// Thread.sleep(r.nextInt(4) * 1000);
			Thread.sleep(1);
			account.addEntry(entry);

			account.setState(AccountStateActive.getInstance());
			return true;
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		return false;
	}
}
