package framework.account;

//
//
// Generated by StarUML(tm) Java Add-In
//
// @ Project : Financial Application Framework
// @ File Name : AccountStateClosed.java
// @ Date : 4/21/2014
// @ Author : Batjargal Batbold, Jose Ardaiz, Ripon Datta
//
//

public class AccountStateClosed implements IAccountState {
	private static AccountStateClosed	instance	= new AccountStateClosed();

	public static AccountStateClosed getInstance() {
		return instance;
	}

	@Override
	public boolean deposit(BaseAccount account, Entry entry) {
		System.err.println("Deposit failed on closed account: " + account);
		return false;
	}

	@Override
	public boolean withdraw(BaseAccount account, Entry entry) {
		System.err.println("Withdraw failed on closed account: " + account);
		return false;
	}

}
