package framework.account;

import java.util.Date;
//
//
// Generated by StarUML(tm) Java Add-In
//
// @ Project : Financial Application Framework
// @ File Name : Entry.java
// @ Date : 4/21/2014
// @ Author : Batjargal Batbold, Jose Ardaiz, Ripon Datta
//
//

public class Entry implements IEntry {
	private double	amount;
	@SuppressWarnings("unused")
	private Date	date;
	public String	description;

	public Entry(double amount, Date date, String description) {
		this.amount = amount;
		this.date = date;
		this.description = description;
	}
	@Override
	public double getAmount() {
		return amount;
	}
	@Override
	public void setAmount(double amount) {
		this.amount = amount;
	}
}
