package framework.account;

//
//
// Generated by StarUML(tm) Java Add-In
//
// @ Project : Financial Application Framework
// @ File Name : IAccountState.java
// @ Date : 4/21/2014
// @ Author : Batjargal Batbold, Jose Ardaiz, Ripon Datta
//
//

public interface IAccountState {
	public boolean deposit(BaseAccount account, Entry entry);

	public boolean withdraw(BaseAccount account, Entry entry);
}
